[package]
name = "TodoList"
version = "1.0.0"
authors = ["Your Name"]

[addresses]
todo_addr = "0x5bd3338c9f09619c16a5207af405b84e98d041c8194ea90c2243be7dba513423"

[dev-addresses]
todo_addr = "0x42"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies] 